# Generated by Django 2.2.6 on 2020-02-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200205_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Tema')),
                ('message', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Brief',
                'verbose_name_plural': 'Briefe',
            },
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images', verbose_name='Photo'),
        ),
    ]
